### ISSUE TITLE
Err Handling Causing Crash

### ISSUE THREAD

**Issue by ninjada** [aarontam/hip-trivia#1]
Neat plugin,

Just been testing it out, but can't get past the beginning stages as /trivia categories causes a crash.

```
[nodemon] starting `node --harmony web.js`
info: Atlassian Connect add-on started at https://b9764c06.ngrok.io
  <-- POST /addon/webhook?name=f5a894efdb6969ff214de238ba8bdda5249c4c8e
/home/vagrant/project/project/node_modules/ac-koa/node_modules/co/index.js:292
    throw err;
          ^
TypeError: Cannot read property 'length' of undefined
    at Object.exports.onCommand (/home/vagrant/project/project/lib/commander.js:81:35)
    at GeneratorFunctionPrototype.next (native)
    at next (/home/vagrant/project/project/node_modules/ac-koa/node_modules/co/index.js:74:21)
    at Object.<anonymous> (/home/vagrant/project/project/node_modules/ac-koa/node_modules/co/index.js:45:5)
    at Object.<anonymous> (/home/vagrant/project/project/node_modules/ac-koa/lib/index.js:95:28)
    at GeneratorFunctionPrototype.next (native)
    at next (/home/vagrant/project/project/node_modules/ac-koa/node_modules/co/index.js:74:21)
    at Object.<anonymous> (/home/vagrant/project/project/node_modules/ac-koa/node_modules/co/index.js:45:5)
    at Application.<anonymous> (/home/vagrant/project/project/node_modules/ac-koa/lib/index.js:100:12)
    at Application.emit (events.js:107:17)
[nodemon] app crashed - waiting for file changes before starting...
```

Haven't been able to nut it out.

Note: I had to make multiple changes to several js files which reported errors on npm run web-dev, basically all due to backtik issues. I've forked and edited a running vers, up to the err from /trivia categories that is.

Culprit seems to be: at Object.exports.onCommand (/home/vagrant/project/project/lib/commander.js:81:35)

Have tried some modifications to the payload.length stuff, but no luck.

**Comment by aarontam** [comment]
Thanks for reporting the issue! I'll take a look, but the categories area was not well-fleshed-out, so there might be some cruft. As for the backtick issues, what version of node are you running? Using the `--harmony` switch should enable support for ES6 templates.

**Comment by ninjada** [comment]
Was using node v12.3.7 or v12.3.14 i think. Pretty sure it had the --harmony switch, guessing v12 has issues? I can try v4 LTS or something.

**Comment by aarontam** [comment]
Thanks! Let me know if that changes anything with the backticks. Also, did the other functions, such as the standard `/trivia` and `/a` (to answer), work?
